name: Fix-release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: "Release version"
        required: true
        type: number

jobs:
  lint:
    uses: despores/shri-infra-homework/.github/workflows/lint.yml@main

  test:
    uses: despores/shri-infra-homework/.github/workflows/test.yml@main

  fix-release:
    runs-on: ubuntu-latest
    env:
      IMAGE: cr.yandex/${{ secrets.CONTAINER_REGISTRY_ID }}/app
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Check if workflow started from release branch
        run: |
            if [[ ! "${GITHUB_REF_NAME}" =~ ^releases/[0-9]+$ ]]; then
            echo "Fix-release workflow started from a wrong branch"
            exit 1
            fi
