name: Test pull-request

on:
  pull_request:
    branches: ["main", "release/**"]
    types: [opened, synchronize, reopened, edited]


jobs:
  lint:
    uses: despores/shri-infra-homework/.github/workflows/lint.yml@main
  
  test:
    uses: despores/shri-infra-homework/.github/workflows/test.yml@main