name: Production

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: "Release version"
        required: true
        type: number

jobs:
  prod:
    runs-on: ubuntu-latest
    env:
      IMAGE: cr.yandex/${{ secrets.CONTAINER_REGISTRY_ID }}/app:${{ inputs.release-version }}_latest
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Login to Container Registry
        run: |
          echo "${{ secrets.OAUTH_KEY }}" | docker login --username oauth --password-stdin cr.yandex

      - name: Check if Container Registry contains docker image
        run: |
          docker manifest inspect ${{ env.IMAGE }}

      - name: Connect to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.KEY }}
          script: |
            curl -H Metadata-Flavor:Google 169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token | \
            cut -f1 -d',' | \
            cut -f2 -d':' | \
            tr -d '"' | \
            docker login --username iam --password-stdin cr.yandex
            docker pull ${{ env.IMAGE }}
            docker run -d -p 3000:3000 ${{ env.IMAGE }}
            
      - name: Comment on Issue
        env:
          BODY: |
            Release pushed to production by ${{ github.triggering_actor }}
        run: |
          ISSUE_NUMBER=$(gh issue list --label "release-${{ inputs.release-version }}" --json number --jq '.[0].number')
          gh issue comment $ISSUE_NUMBER \
          --body "${{ env.BODY }}" \

