name: Releasing

on:
  workflow_dispatch:

jobs:
  lint:
    uses: despores/shri-infra-homework/.github/workflows/lint.yml@main

  test:
    uses: despores/shri-infra-homework/.github/workflows/test.yml@main

  create-release:
    runs-on: ubuntu-latest
    env:
      IMAGE: cr.yandex/${{ secrets.CONTAINER_REGISTRY_ID }}/app
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release branch
        run: git checkout -b releases/${{ github.run_number }}

      - name: Login to Yandex Cloud
        run: |
          echo "${{ secrets.OAUTH_KEY }}" | docker login --username oauth --password-stdin cr.yandex

      - name: Create docker image
        run: docker build -t ${{ env.IMAGE }}:${{ github.run_number }} -t ${{ env.IMAGE }}:${{ github.run_number }}_latest .

      - name: Upload docker image to Container Registry
        run: docker push --all-tags ${{ env.IMAGE }}

      - name: Push release branch
        run: git push -u origin releases/${{ github.run_number }}

      - name: Get commit list
        id: commits
        run: echo "commits=$(git log --pretty=format:"%H by %an with message %s" $(git describe --tags --abbrev=0)..HEAD)" >> "$GITHUB_OUTPUT"


      - name: Create tag
        run: |
          git checkout main
          git tag release-version-${{ github.run_number }}
          git push origin --tags
      
      - name: Create Issue
        env:
          BODY: |
            Release from ${{ github.triggering_actor }}
            Commit list from previous release:
            ${{ steps.commits.outputs.commits }}
            Docker image in container registry: ${{ env.IMAGE }}
        run: |
          gh issue create \
          --title "Version ${{ github.run_number }}" \
          --assignee "${{ github.triggering_actor }}" \
          --body "${{ env.BODY }}"


