name: Testing pull request

on:
  pull_request:
    branches: ["main", "release/**"]
    types: [opened, synchronize, reopened, edited]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: "npm"
      
      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test
 
